#!/usr/bin/python3

import cgi
import subprocess

print("content-type: text/html")
print()

f = cgi.FieldStorage()
client_input = f.getvalue("x")
command = client_input.split()
if command[0] == "1":
    deployment_name = command[2]
    image_name = command[1]
    cmd = "kubectl create deployment " + (deployment_name) + " --image=" + (image_name)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "2":
    pod_name = command[2]
    image_name = command[1]
    cmd = "kubectl run " + (pod_name) + " --image=" + (image_name)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "3":
    pod_name = command[1]
    cmd = "kubectl delete pod " + (pod_name)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "4":
    deployment_name = command[1]
    cmd = "kubectl delete deployment " + (deployment_name)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "5":
    deployment_name = command[1]
    port_no = command[2]
    Expose_type =  command[3]
    cmd = "kubectl expose deployment " + (deployment_name) + " --port=" + (port_no) + " --type=" + (Expose_type)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "6":
    deployment_name = command[1]
    replica = command[2]
    cmd = "kubectl scale deployment " + (deployment_name) + " --replicas=" + (replica)
    output = subprocess.getoutput("sudo " + cmd + " --kubeconfig admin.conf")
    print(output)
elif command[0] == "7":
    cmd = "sudo kubectl get pods --kubeconfig admin.conf"
    output = subprocess.getoutput(cmd)
    print(output)
elif command[0] == "8":
    cmd = "kubectl get deployments --kubeconfig admin.conf"
    output = subprocess.getoutput("sudo " + cmd)
    print(output)
elif command[0] == "9":
    cmd = "kubectl get svc --kubeconfig admin.conf"
    output = subprocess.getoutput(cmd)
    print(output)
elif command[0] == "10":
    cmd = "kubectl delete all --all --kubeconfig admin.conf"
    output = subprocess.getoutput("sudo " + cmd)
    print(output)
elif command[0] == "404":
    print("command not found")


  
 * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
        }


        .sci_footer li {
            list-style: none;
        }

        .quick_links li {
            list-style: none;
        }

        html {
            font-size: 62.5%;
        }

        footer {
            height: auto;
            padding: 5rem 10rem;
            display: flex;
            width: 100vw;
            background-color: black;
            color: white;
            font-size: 1.3rem;
            justify-content: space-between;
            flex-wrap: wrap;

        }

        footer .footer_container {
            display: flex;
            flex-direction: row;
        }

        footer .footer_container .about_us {
            margin-right: 3rem;
            width: 40%;
        }



        footer .footer_container h2 {
            position: relative;
            font-weight: 500;
            margin-bottom: 1.5rem;
        }

        footer .footer_container h2::before {
            content: ' ';
            position: absolute;
            bottom: -.5rem;
            left: 0;
            width: 5rem;
            height: .2rem;
            background: #f00;
        }

        footer p {
            color: #999;

        }

        .sci_footer {
            margin-top: 2rem;
            display: flex;
        }

        .sci_footer li a {
            display: inline-block;
            width: 4rem;
            height: 4rem;
            background: #222;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-right: 1rem;
            text-decoration: none;
            border-radius: .4rem;
        }

        .sci_footer li a:hover {
            background: red;
        }

        .quick_links {
            width: 25%;
            margin-left: 41rem;
        }

        .quick_links ul li {
            color: #999;
            text-decoration: none;
            margin-bottom: 1rem;

        }

        .quick_links ul li:hover {
            color: #fff;
        }

        .contact_us {
            margin-left: 28rem;
        }

        .contact_us .info li {
            display: flex;
            margin-bottom: 1.6rem;

        }

        .contact_us .info li span:nth-child(1) {
            color: white;
            font-size: 2rem;
            margin-right: 1rem;
        }

        .contact_us .info li span {
            color: #999;
        }

        .contact_us .info li a {
            color: #999;
            text-decoration: none;
        }

        .contact_us .info li a:hover {
            color: #fff;
        }

        .copyrighttext {
            width: 100%;
            background: #181818;
            padding: .8rem 10rem;
            text-align: center;
            color: #999;
            word-spacing: .8ch;
        }

        @media(max-width: 991px) {
            footer {
                padding: 4rem;
            }

            footer .footer_container {
                flex-direction: column;
            }

            footer .footer_container .about_us {
                margin-right: 0;
                margin-bottom: 4rem;
            }
        }



/* Add a black background color to the top navigation */
.topnav {
  background-color: black;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a.active {
  background-color: #3c9b9e;
  color: white;
}
.topnav a.right {
  float: right;
}
.center {
  margin-top: 10%;
  margin-bottom: 10%;
  text-align: center;
  float: center;
  color: black;
  font-size: 25px;
}

.container {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  color: black;
  background-color: #3c9b9e;
  
}
.container .box {
  position: relative;
  width: 280px;
  padding: 30px;
  background:white;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
  border-radius: 4px;
  margin: 10px;
  box-sizing: border-box;
  overflow: hidden;
}
.container .box .icon {
  position: relative;
  width: 70px;
  height: 70px;
  color: #fff;
  background: #000;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-left: 60px;
  margin-bottom: 20px;
  border-radius: 50%;
  font-size: 40px;
  font-weight: 700;
  transition: 1s;
}

.container .box:nth-child(1) .icon {
  background-color: yellowgreen;
}

/* image clip path part*/
.container .box:nth-child(1) .icon img,
.container .box:nth-child(2) .icon img,
.container .box:nth-child(3) .icon img,
.container .box:nth-child(4) .icon img,
.container .box:nth-child(5) .icon img {
  clip-path: circle(50% at 50% 50%);
}

/* image clip path part*/
.container .box:nth-child(1):hover .icon {
  box-shadow: 0 0 0 400px yellowgreen;
}

.container .box:nth-child(2) .icon {
  background-color: SlateBlue;
}
.container .box:nth-child(2):hover .icon {
  box-shadow: 0 0 0 400px SlateBlue;
}

.container .box:nth-child(3) .icon {
  background-color: Tomato;
}
.container .box:nth-child(3):hover .icon {
  box-shadow: 0 0 0 400px Tomato;
}

.container .box:nth-child(4) .icon {
  background-color: purple;
}
.container .box:nth-child(4):hover .icon {
  box-shadow: 0 0 0 400px purple;
}

.container .box:nth-child(5) .icon {
  background-color: MediumSeaGreen;
}
.container .box:nth-child(5):hover .icon {
  box-shadow: 0 0 0 400px MediumSeaGreen;
}
.container .box .content {
  position: relative;
  z-index: 1;
  transition: 0.5s;
}

h2 {
  font-size: 17px;
}
a{
  margin-top: 10px;
  font-size: 15px;
}
h3 {
  text-align: center;
margin-top: 25px;}

.headingtm {
  background-color: #fff;
  align-self: center;
  padding-top: 15px;
  padding-bottom: 15px;
  padding-left: 42%;
  font-size: medium;
}

.info {
  position: relative;
  align-self: center;
  text-align: center;
  padding-left: 30%;
  padding-right: 30%;
  padding-top: 15%;
  color: #fff;
  font-size: xx-large;
}

/* input area */
.areaip {
  height: 1800px;
  padding-left: 30%;
  padding-top: 550px;
}

.internalip {
  position: relative;
  align-self: center;
}

button {
  align-self: center;
  margin-left: 17%;
  font-size: x-large;
  font-family: 'Courier New', Courier, monospace, Impact;
  color: #fff;
  padding: 10px;
  width: 20%;
  border-radius: 35px;
  border-style: solid;
  border-width: medium;
  border-color: #3c9b9e;
  background-color: transparent;
  cursor: pointer;
}  

button:hover {
  box-shadow: 0 2px 20px 0 #8ce3e5 inset, 0 2px 20px 0 #8ce3e5,
              0 2px 20px 0 #8ce3e5 inset, 0 2px 20px 0 #8ce3e5;
}

input {
  align-self: center;
  text-align: center;
  font-size: x-large;
  font-family: 'Courier New', Courier, monospace, Impact;
  color: #fff;
  padding: 25px;
  padding-left: 30px;
  padding-right: 30px;
  width: 800px;
  border-radius: 35px;
  border-style: solid;
  border-width: medium;
  border-color: #3c9b9e;
  background-color: transparent;
}

input:hover {
  box-shadow: 0 2px 20px 0 #8ce3e5 inset, 0 2px 20px 0 #8ce3e5,
              0 2px 20px 0 #8ce3e5 inset, 0 2px 20px 0 #8ce3e5;
}

::placeholder {
  color: #fff;
  font-size: xx-large;
  text-align: center;
}
.output{
  
  color: yellow;
  font-size: 40px;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="style1.css">
    <link rel="stylesheet" href="footer.css">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>

<body >
    <div>
        
        <div class="topnav">
            <a class="active" href="#home">Summer Trainees</a>
            <a  href="#home">Home</a>
            <a href="#contact">Contact</a>
            <a href="#about">About</a>
            <a class="right" href="#login">Login</a>
            <a class="right" href="#login">Signup</a>
        </div>
		<body background="k8.png">

        <div class="info">
            <h1> Kubernetes Hub!!</h1><br>
            <p>Kubernetes is a portable, extensible, open-source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation. It has a large, rapidly growing ecosystem. Kubernetes services, support, and tools are widely available.  </p>
        </div>



<script>
function lw() {

  var i = document.getElementById("id1").value
  var idd = "0"
  var final = ""
  if (((i.includes("deployments")) || (i.includes("deploy")) || (i.includes("deployment"))) && ((i.includes("create")) || (i.includes("generate")) || (i.includes("build")))) {
    	var image = prompt("Enter image name: ")
	var deployment_name = prompt("Enter Deployment name: ")
	var idd = "1"
	var final = idd + " " + image + " " + deployment_name 
	
    }

  else if (((i.includes("pods")) || (i.includes("pod"))) && ((i.includes("create")) || (i.includes("generate")) || (i.includes("build")))) {
	var image = prompt("Enter image name: ")
	var pod_name = prompt("Enter pod name: ")
	var idd = "2"
	var final = idd + " " + image + " " + pod_name
	
	}

  else if (((i.includes("pods")) || (i.includes("pod"))) && ((i.includes("delete")) || (i.includes("remove")) || (i.includes("detach")))) {
	var pod_name = prompt("Enter pod name: ")
	var idd = "3"
	var final = idd + " " + pod_name
	
	}

  else if (((i.includes("deployments")) || (i.includes("deploy")) || (i.includes("deployment"))) && ((i.includes("delete")) || (i.includes("remove")) || (i.includes("detach")))) {
	var deployment_name = prompt("Enter Deployment name: ")
	var idd = "4"
	var final = idd + " " + deployment_name
	
    }

  else if (((i.includes("deployments")) || (i.includes("deploy")) || (i.includes("deployment"))) && ((i.includes("expose"))  || (i.includes("display")))) {
	var deployment_name = prompt("Enter Deployment name: ")
	var port_no = prompt("Enter port no on which you want yo export your deployment: ")
	var expose_type = prompt(" 1. NodePort \n 2. ClusterIP \n 3.External \n Enter the type which you want to export ")
	var idd = "5"
	var final = idd + " " + deployment_name + " " + port_no + " " + expose_type
	
    }

  else if (((i.includes("deployments")) || (i.includes("deploy")) || (i.includes("deployment"))) && ((i.includes("scale")) || (i.includes("increase")) || (i.includes("decrease")) || (i.includes("scale up")) || (i.includes("scale down")))) {
	var deployment_name = prompt("Enter Deployment name: ")
	var replica = prompt("Enter no. of replicas you need : ")
	var idd = "6"
	var final = idd + " " + deployment_name + " " + replica
	
    }

  else if (((i.includes("pods")) || (i.includes("pod"))) && ((i.includes("show")) || (i.includes("get")) || (i.includes("list")))) {
	var idd = "7"
	var final = idd 
	
	}

  else if (((i.includes("deployments"))|| (i.includes("deployment")) || (i.includes("deploy"))) && ((i.includes("show")) || (i.includes("get")) || (i.includes("list")))) {
	var idd = "8"
	var final = idd 
	
	}
  else if (((i.includes("services")) || (i.includes("services")) || (i.includes("svc"))) && ((i.includes("show")) || (i.includes("get")) || (i.includes("list")))) {
	var idd = "9"
	var final = idd 
	
	}

  else if (((i.includes("all")) || (i.includes("everything"))) && ((i.includes("delete")) || (i.includes("remove")) || (i.includes("destroy")))) {
	var idd = "10"
	var final = idd 
	
}

  else {
	var idd = "404"
	var final = idd 
	
  }

var xhr = new XMLHttpRequest();
xhr.open("GET", "http://192.168.0.107/cgi-bin/backend.py?x=" + final, true);

xhr.send();

// Output from above url

xhr.onload = function () {
	var output = xhr.responseText;
	document.getElementById("d1").innerHTML = output;
}

}
</script>

        <div class="areaip">
             <!--Input Section-->
            <div class="internalip">
                <input type="input" id="id1" class="text_field" placeholder="Enter Your Kubernetes Command"><br>
                <br> <br>
                <button onclick="lw()" class="btn">Press_Here</button>
	 <div id="d1" class="output" >OUTPUT</div>
            </div>
        </div>
    </div>

<div class="headingtm">
    <h1>!! Team 'THE COSMOPOLITAN' !!</h1>
</div>
<!--   Pre Footer Section -->
<div class="container">
	
    <div class="box">
        
        <div class="box">

        <h2>Name : Adamaya Sharma <br>
        Summer Intern At LinuxWorld <br></h2>
          
       
